start: formula

formula: TRUE
       | FALSE
       | VAR
       | and
       | or
       | diamond
       | box
       | mu
       | nu

VAR: UCASE_LETTER
AL: (LCASE_LETTER) (LCASE_LETTER|DIGIT|"_")*

TRUE: "true"
FALSE: "false"
and: "(" formula "&&" formula ")"
or: "(" formula "||" formula ")"
diamond: "<" AL ">" formula
box: "[" AL "]" formula
mu: "mu" VAR "." formula
nu: "nu" VAR "." formula

%import common.UCASE_LETTER
%import common.LCASE_LETTER
%import common.DIGIT